# Site settings
name: Loan Vulliard
description: > 
  If I'm not in front of my computer doing genomics, I'm probably somewhere playing music.\n
  <i>Currently predoctoral fellow in the<a href="https://menchelab.com/">group of Jörg Menche.</a></i>
url: "http://vulliard.loan"
title: Loan Vulliard

# Delete the lines you don't need
# about 5 elements are recomended
github_username: lvulliard
linkedin_username: vulliard
# facebook_username: imprevuslyon
# email: loan.vulliard@gmail.com
#codepen_username: your_codepen_username_goes_here
#vk_username: your_vk_username_goes_here
twitter_username: LVulliard
#google_plus_username: your_google_plus_username_goes_here
#vine_username:  your_vine_username_goes_here
#instagram_username:  your_instagram_username_goes_here
#flickr_username: your_flickr_username_goes_here
#steam_username: your_steam_username_goes_here
#stack_of_username: your_stack_overflow_account_id_number_goes_here
#reddit_username: your_reddit_username_goes_here
#medium_username:  your_medium_username_goes_here
#tumblr_username: your_tumblr_username_goes_here
#weibo_username: your_weibo_username_goes_here
#lastfm_username: your_lastfm_username_goes_here
#blog_url: "/blog"
#public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"
scholar_username: QFdroc8AAAAJ
soundcloud_username: loan-vulliard

avatar: yes
avatar_img_path: "imgs/pic.jpeg"


front_img: yes
#front_img_path: "https://static.pexels.com/photos/39811/pexels-photo-39811.jpeg"
front_img_path: "imgs/background.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty
